// Generated by cms/scripts/sync-website-typography.mjs from website/src/styles/typography.css.
export const websiteTextStyles = [
  {
    "id": "headings-h1",
    "label": "Headings/H1",
    "className": "text-headings-h1"
  },
  {
    "id": "headings-h1-alt",
    "label": "Headings/H1 Alt",
    "className": "text-headings-h1-alt"
  },
  {
    "id": "headings-h1-narrow",
    "label": "Headings/H1 - Narrow",
    "className": "text-headings-h1-narrow"
  },
  {
    "id": "headings-h1-ultranarrow",
    "label": "Headings/H1 - Ultranarrow",
    "className": "text-headings-h1-ultranarrow"
  },
  {
    "id": "headings-h2",
    "label": "Headings/H2",
    "className": "text-headings-h2"
  },
  {
    "id": "headings-h3",
    "label": "Headings/H3",
    "className": "text-headings-h3"
  },
  {
    "id": "headings-h4",
    "label": "Headings/H4",
    "className": "text-headings-h4"
  },
  {
    "id": "headings-h5",
    "label": "Headings/H5",
    "className": "text-headings-h5"
  },
  {
    "id": "headings-h6",
    "label": "Headings/H6",
    "className": "text-headings-h6"
  },
  {
    "id": "display-large",
    "label": "Display/Large",
    "className": "text-display-large"
  },
  {
    "id": "display-medium",
    "label": "Display/Medium",
    "className": "text-display-medium"
  },
  {
    "id": "display-small",
    "label": "Display/Small",
    "className": "text-display-small"
  },
  {
    "id": "body-large",
    "label": "Body/Large",
    "className": "text-body-large"
  },
  {
    "id": "body-medium",
    "label": "Body/Medium",
    "className": "text-body-medium"
  },
  {
    "id": "body-small",
    "label": "Body/Small",
    "className": "text-body-small"
  },
  {
    "id": "navigation-large-paragraph-link",
    "label": "Navigation/Large Paragraph Link",
    "className": "text-navigation-large-paragraph-link"
  },
  {
    "id": "navigation-medium-paragraph-link",
    "label": "Navigation/Medium Paragraph Link",
    "className": "text-navigation-medium-paragraph-link"
  },
  {
    "id": "navigation-small-paragraph-link",
    "label": "Navigation/Small Paragraph Link",
    "className": "text-navigation-small-paragraph-link"
  },
  {
    "id": "navigation-navigation-link",
    "label": "Navigation/Navigation Link",
    "className": "text-navigation-navigation-link"
  }
] as const
