import test from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { initHeroMotion } from '../src/scripts/hero-motion.ts';

test('hero motion can pause, follows reduced motion, and initializes only once', () => {
  const window = new Window();
  globalThis.window = window;
  globalThis.document = window.document;
  const preference = new window.EventTarget();
  preference.matches = false;
  window.matchMedia = () => preference;
  document.body.innerHTML = '<section data-hero><button class="hero-motion-control" hidden></button></section>';
  const root = document.querySelector('section');
  const button = root.querySelector('button');
  initHeroMotion(root);
  initHeroMotion(root);
  assert.equal(root.dataset.motionReady, 'true');
  assert.equal(button.hidden, false);
  button.click();
  assert.equal(button.getAttribute('aria-pressed'), 'true');
  assert.equal(root.dataset.paused, 'true');
  assert.equal(button.textContent, 'Resume animation');
  preference.matches = true;
  preference.dispatchEvent(new window.Event('change'));
  assert.equal(root.dataset.motionReady, undefined);
  assert.equal(button.hidden, true);
  preference.matches = false;
  preference.dispatchEvent(new window.Event('change'));
  assert.equal(root.dataset.paused, 'true');
  button.click();
  assert.equal(button.getAttribute('aria-pressed'), 'false');
  assert.equal(button.textContent, 'Pause animation');
  window.close();
});
