import test from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { initHeroMotion } from '../src/scripts/hero-motion.ts';

test('hero motion initializes without a control and follows reduced motion and page visibility', () => {
  const window = new Window();
  globalThis.window = window;
  globalThis.document = window.document;
  const preference = new window.EventTarget();
  preference.matches = false;
  window.matchMedia = () => preference;
  document.body.innerHTML = '<section data-hero></section>';
  const root = document.querySelector('section');
  initHeroMotion(root);
  initHeroMotion(root);
  assert.equal(root.dataset.motionReady, 'true');
  Object.defineProperty(document, 'hidden', { configurable: true, value: true });
  document.dispatchEvent(new window.Event('visibilitychange'));
  assert.equal(root.dataset.paused, 'true');
  preference.matches = true;
  preference.dispatchEvent(new window.Event('change'));
  assert.equal(root.dataset.motionReady, undefined);
  preference.matches = false;
  preference.dispatchEvent(new window.Event('change'));
  assert.equal(root.dataset.paused, 'true');
  assert.equal(root.dataset.motionReady, 'true');
  Object.defineProperty(document, 'hidden', { configurable: true, value: false });
  document.dispatchEvent(new window.Event('visibilitychange'));
  assert.equal(root.dataset.paused, 'false');
  window.close();
});
